### ISSUE TITLE
Companion crashing LightingController

### ISSUE THREAD

**Issue by tacvideo** [thargy/companion-module-thelightingcontroller#1]
Been having a lot of stability issues with LightingController for awhile now, I've always just assumed it was LightingController (LC), even had them helping me out with stabilizing that environment. But I've just noticed over the past few weeks that if I turn off the Connection in Companion, LC doesn't crash.

It'll happen randomly, like middle of the night with nobody even in the building. But over the past few weeks I've disabled the connection when not using the system, then like this past Sunday morning, I enabled the connection and LC crashed 3 times in 30 minutes, then luckily was stable till end of service.

I have no idea where to look for logs (on the LC side) that might help pin point anything... I have been collecting the usual Apple Crash logs, but the LightingController guys (Chauvet) said they were not helpful.

We were on an old 2012 Mac Mini, but recently I put an M1 with latest OS in place to see if that made any difference - it didn't.

I'd really like to stay on LC, but at this point I'm under pressure to replace it which is a ton of work!

**Comment by thargy** [comment]
Hi, please could you raise this issue at https://github.com/bitfocus/companion-module-thelightingcontroller/issues.  This was my original development repo, but when it was accepted by bitfocus it became part of their core modules and is now maintained there.  I should probably make this repo private to avoid confusion.

I am not associated with Chauvet, Showtec or the Lighting Controller in anyway; I developed this module for use with the system my church uses, and shared it with the community.  Sadly, the last time I looked at this was in March 2021.

However, have you seen [this issue](https://github.com/bitfocus/companion-module-thelightingcontroller/issues/2).  The details are a little vague, but if I recall correctly the latest version of the Lighting Controller (aka QuickDMX) notifies you of all button changes, even if those buttons are on pages that are purportedly not visible to external apps.  That was causing my code to trigger a refresh to update it's db of available buttons, which was causing the spamming of refreshes.  I fixed that issue, but the recommendation was to ensure you are exposing _all_ your button pages.

The other issue is that the WebAPI that exposed by their software is synchronous and blocking (which is really poor design) and so lots of traffic can slow down the lighting controller, and cause it to block for periods (though it hasn't really crashed that much for me on PC).  When you raise this issue, ensure you have Companion set to log debug messages and then see if there's anything being reported in the companion logs.  If those logs are getting spammed it could be that you have way too much traffic going on and the WebAPI is blocking.  The module does output plenty of useful debug logs which might help us figure out what's going on.

When you raise the issue at the formal repo, I will move this response over too.
